# Experimental Solution builder

project:
  name: Wired_app

  src_files:


  src_files_exclude_windows:
    - code/utils/directory_nix.cpp
    - code/utils/directory_mac.mm

  inc_dirs:

  inc_dirs_nix:
    - /usr/local/include

  inc_dirs_windows:
    - code/utils/

  lib_dirs:
    - /usr/local/lib

  lib_link:
    
